### ISSUE TITLE
Spelling!

### ISSUE THREAD

**Issue by demianriccardi** [sdrasmu12/Chem452-Excrecises#1]
it looks like you might need to pursue a phd in spelling.

**Comment by sdrasmu12** [comment]
Not a spelling mistake, pun on exercises and excrement since you say shit a lot.

**Comment by demianriccardi** [comment]
Hmmm....  That makes sense I guess.  I do say shit a lot, but that is down in the trenches of doing useful work without useful results.  Excresises in the title may be a little too much of a shitty shadow over it all.
